### PR TITLE
WIP Updated logo

### LINKED ISSUE #85: 2021 / Change logo to 2021 edition

### PR DESCRIPTION
**Pull request by FilipePintoReis**
Closes #85

### CODE REVIEW

**Comment by FilipePintoReis** [comment]
Don't approve this PR just yet, we need to change the logo so it doesn't diffuse into the background

**Review by ZeCarlosCoutinho — APPROVED** [review]
Seems fine :)

**Comment by ZeCarlosCoutinho** [comment]
Ahahah just saw the comment now. Gotta find how to unnaprove

**Comment by ZeCarlosCoutinho** [comment]
The logo has been updated in https://github.com/alumniei/jobit/pull/96

**Pull request closed without merging**
